name: gendiff
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: action/setup-node@v4
      - uses: action/setup-eslint@v4
      - run: npm install
      - run: make lint
