name: gendiff
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: action/setup-node@v4
      - run: | 
        npm install
        npm install eslint --save-dev
      - run: make lint
